# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"%\n\x04User\x12\x0b\n\x03_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\"\"\n\x0eGetUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\".\n\x11\x43reateUserRequest\x12\x19\n\x04User\x18\x01 \x01(\x0b\x32\x0b.users.User\".\n\x11UpdateUserRequest\x12\x19\n\x04User\x18\x01 \x01(\x0b\x32\x0b.users.User2\xac\x01\n\x0bUserService\x12/\n\x07GetUser\x12\x15.users.GetUserRequest\x1a\x0b.users.User\"\x00\x12\x35\n\nCreateUser\x12\x18.users.CreateUserRequest\x1a\x0b.users.User\"\x00\x12\x35\n\nUpdateUser\x12\x18.users.UpdateUserRequest\x1a\x0b.users.User\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=22
  _USER._serialized_end=59
  _GETUSERREQUEST._serialized_start=61
  _GETUSERREQUEST._serialized_end=95
  _CREATEUSERREQUEST._serialized_start=97
  _CREATEUSERREQUEST._serialized_end=143
  _UPDATEUSERREQUEST._serialized_start=145
  _UPDATEUSERREQUEST._serialized_end=191
  _USERSERVICE._serialized_start=194
  _USERSERVICE._serialized_end=366
# @@protoc_insertion_point(module_scope)
